# Generates Guardian Mesh demo scenario assets (Windows SAPI + System.Drawing).
$ErrorActionPreference = "Stop"
$root = Join-Path $PSScriptRoot ".."
$audioDir = Join-Path $root "test-data"
$sampleDir = Join-Path $root "samples"
New-Item -ItemType Directory -Force -Path $audioDir, $sampleDir | Out-Null

Add-Type -AssemblyName System.Speech
Add-Type -AssemblyName System.Drawing

function Write-ScamAudio($path, $text) {
  $synth = New-Object System.Speech.Synthesis.SpeechSynthesizer
  $synth.SetOutputToWaveFile($path)
  $synth.Speak($text)
  $synth.Dispose()
  Write-Output "Audio: $path"
}

# Scenario A — IRS scam (existing)
Write-ScamAudio (Join-Path $audioDir "sentinel-scam-call.wav") `
  "Hello Margaret, this is Officer Smith from the IRS. Your social security number has been suspended due to suspicious activity. You must pay five thousand dollars in gift cards today or we will send police to your home."

# Scenario C — fake Microsoft support
Write-ScamAudio (Join-Path $audioDir "scenario-c-support-call.wav") `
  "Hello, this is Microsoft security support. We detected a virus on your computer. Please install AnyDesk and give us remote access immediately, or your bank accounts will be drained within one hour."

# Scenario D — grandparent scam
Write-ScamAudio (Join-Path $audioDir "scenario-d-grandparent.wav") `
  "Grandma, it's me, your grandson. I'm in jail and I need bail money right now. Please wire eight thousand dollars and do not tell mom or dad. This is urgent."

# Scenario E — crypto scam call
Write-ScamAudio (Join-Path $audioDir "scenario-e-crypto.wav") `
  "Margaret, this is your investment advisor. Bitcoin is guaranteed to double tomorrow. Send your retirement savings to this wallet address now before the window closes. Do not discuss with your bank."

# Scenario F — fake healthcare billing (image)
$healthPath = Join-Path $sampleDir "scenario-f-healthcare.png"
$bmp = New-Object System.Drawing.Bitmap 800, 520
$g = [System.Drawing.Graphics]::FromImage($bmp)
$g.Clear([System.Drawing.Color]::White)
$title = New-Object System.Drawing.Font("Arial", 20, [System.Drawing.FontStyle]::Bold)
$body = New-Object System.Drawing.Font("Arial", 13)
$g.DrawString("MEDICARE BENEFITS SUSPENSION NOTICE", $title, [System.Drawing.Brushes]::DarkRed, 40, 30)
$g.DrawString("Patient: Margaret Thompson", $body, [System.Drawing.Brushes]::Black, 40, 90)
$g.DrawString("Your Medicare Part B will be cancelled unless you verify your Social Security number.", $body, [System.Drawing.Brushes]::Black, 40, 130)
$g.DrawString("Pay $299 processing fee by phone with gift cards to restore coverage.", $body, [System.Drawing.Brushes]::Black, 40, 170)
$g.DrawString("Call 1-888-555-0177 immediately. Do not contact your doctor.", $body, [System.Drawing.Brushes]::Black, 40, 210)
$bmp.Save($healthPath, [System.Drawing.Imaging.ImageFormat]::Png)
$g.Dispose(); $bmp.Dispose()
Write-Output "Image: $healthPath"

# Scenario G — safe family check-in
Write-ScamAudio (Join-Path $audioDir "scenario-g-safe-checkin.wav") `
  "Good morning. I slept well last night. I had oatmeal for breakfast and I plan to walk in the garden later. My memory feels fine today. Caregiver Ben checked in and dinner is tomorrow at six."

# Scenario W — suspicious but not confirmed fraud
Write-ScamAudio (Join-Path $audioDir "scenario-w-suspicious-verify.wav") `
  "Margaret, this is your electric company. Your account needs urgent verification. Please confirm your date of birth and payment method. Call 1-800-555-0199 to verify your account."

# Scenario H — safe pharmacy receipt (image)
$safePath = Join-Path $sampleDir "scenario-h-safe-receipt.png"
$bmp2 = New-Object System.Drawing.Bitmap 700, 400
$g2 = [System.Drawing.Graphics]::FromImage($bmp2)
$g2.Clear([System.Drawing.Color]::White)
$g2.DrawString("SUNRISE PHARMACY RECEIPT", $title, [System.Drawing.Brushes]::DarkGreen, 40, 30)
$g2.DrawString("Patient: Margaret Thompson", $body, [System.Drawing.Brushes]::Black, 40, 90)
$g2.DrawString("Prescription refill Lisinopril 10mg", $body, [System.Drawing.Brushes]::Black, 40, 130)
$g2.DrawString("Copay paid 15 dollars. Thank you for your visit.", $body, [System.Drawing.Brushes]::Black, 40, 170)
$g2.DrawString("Questions? Call your caregiver Ben at 1-555-0142.", $body, [System.Drawing.Brushes]::Black, 40, 210)
$bmp2.Save($safePath, [System.Drawing.Imaging.ImageFormat]::Png)
$g2.Dispose(); $bmp2.Dispose()
Write-Output "Image: $safePath"

# Scenario B invoice already generated by generate-sample-invoice.ps1
Write-Output "Done. Run generate-sample-invoice.ps1 if fake-bank-invoice.png is missing."
